
include(TargetMacros)
#add_mpi_unit_test(Test_CD_SVD 2 "${CMAKE_SOURCE_DIR}/../inputs/h2o.nwx")
#add_mpi_unit_test(Test_CCSD_CD 2 "${CMAKE_SOURCE_DIR}/../inputs/h2o.nwx")
# add_mpi_unit_test(Test_CCSD_CD_RM 2 "${CMAKE_SOURCE_DIR}/../inputs/h2o.nwx")
# add_mpi_unit_test(Test_CCSD_CD_SVD 2 "${CMAKE_SOURCE_DIR}/../inputs/h2o.nwx")
#add_mpi_unit_test(Test_CCSD_Spin 2 "${CMAKE_SOURCE_DIR}/../inputs/h2o.nwx")
#add_mpi_unit_test(Test_CCSD_Lambda 2 "${CMAKE_SOURCE_DIR}/../inputs/h2o.nwx")
#add_mpi_unit_test(Test_EOMCCSD 2 "${CMAKE_SOURCE_DIR}/../inputs/h2o.nwx")
# add_mpi_unit_test(Test_EOMCCSD_Fast 2 "${CMAKE_SOURCE_DIR}/../inputs/h2o.nwx")
# add_mpi_unit_test(Test_Left_EOMCCSD 2 "${CMAKE_SOURCE_DIR}/../inputs/h2o.nwx")
# add_mpi_unit_test(Test_EOM_Gradients 2 "${CMAKE_SOURCE_DIR}/../inputs/h2o.nwx")
# add_mpi_unit_test(Test_DAG_CCSD 2 "${CMAKE_SOURCE_DIR}/../inputs/h2o.nwx")
