
//------------------------------------------------------------------------------
// Copyright (C) 2016, Pacific Northwest National Laboratory
// This software is subject to copyright protection under the laws of the
// United States and other countries
//
// All rights in this computer software are reserved by the
// Pacific Northwest National Laboratory (PNNL)
// Operated by Battelle for the U.S. Department of Energy
//
//------------------------------------------------------------------------------
#ifndef TAMM_TENSOR_COMMON_H_
#define TAMM_TENSOR_COMMON_H_
/**
 * Defines here abstract things that should come from the build
 * system
 */

#include <stddef.h>
#include <stdint.h>
// #include "tensor/cmake_tamm_headers.h"  //generated by cmake

typedef int64_t Fint;
typedef Fint F77Integer; /*for now to get compilation to work*/
typedef Fint BlasInt; /*blas integer size could be different*/
typedef uint32_t Tile;

#define FORTRAN_FUNC(fname, fNAME) fname##_

#ifdef __cplusplus
#define EXTERN_C extern "C"
#else
#define EXTERN_C
#endif  // extern for c++

#define USE_FORTRAN_FUNCTIONS 1
#endif  // TAMM_TENSOR_COMMON_H_
