#define EQUALS                           1
#define TIMESEQUAL                       2
#define PLUSEQUAL                        3
#define MINUSEQUAL                       4
#define PLUS                             5
#define MINUS                            6
#define TIMES                            7
#define LBRACE                           8
#define RBRACE                           9
#define COMMA                           10
#define ID                              11
#define ICONST                          12
#define FCONST                          13
#define FRACCONST                       14
#define RANGE                           15
#define SEMI                            16
#define INDEX                           17
#define ARRAY                           18
#define LBRACKET                        19
#define RBRACKET                        20
#define COLON                           21
#define LPAREN                          22
#define RPAREN                          23
#define EXPAND                          24
#define VOLATILE                        25
#define ITERATION                       26
