# Generates and installs tamm/tamm_config.hpp (from tamm_config.hpp.in), using the values
# CMakeBuild resolved and passed to this sub-build. Included from src/tamm/CMakeLists.txt.

set(TAMM_CONFIG_TEXT "")
set(TAMM_CONFIG_VALUE_COLUMN 26) # values start at this column, as in print_execution_info()

# Appends text (one or more lines) to TAMM_CONFIG_TEXT, escaped for a C++ string literal.
function(tamm_config_append __line)
  string(REPLACE "\\" "\\\\" __line "${__line}")
  string(REPLACE "\"" "\\\"" __line "${__line}")
  string(REPLACE "\n" "\\n" __line "${__line}")
  set(TAMM_CONFIG_TEXT "${TAMM_CONFIG_TEXT}${__line}\\n" PARENT_SCOPE)
endfunction()

# Appends "<indent><label>:<padding><value>". Values line up in one column; a label without a
# value starts a group.
function(tamm_config_line __indent __label __value)
  set(__line "${__indent}${__label}:")
  if(NOT "${__value}" STREQUAL "")
    string(LENGTH "${__line}" __len)
    while(__len LESS TAMM_CONFIG_VALUE_COLUMN)
      string(APPEND __line " ")
      math(EXPR __len "${__len} + 1")
    endwhile()
    if(__len EQUAL TAMM_CONFIG_VALUE_COLUMN)
      string(APPEND __line "${__value}")
    else()
      string(APPEND __line " ${__value}")
    endif()
  endif()
  tamm_config_append("${__line}")
  set(TAMM_CONFIG_TEXT "${TAMM_CONFIG_TEXT}" PARENT_SCOPE)
endfunction()

function(tamm_config_blank)
  set(TAMM_CONFIG_TEXT "${TAMM_CONFIG_TEXT}\\n" PARENT_SCOPE)
endfunction()

function(tamm_config_enabled __out __var)
  if(${__var})
    set(${__out} enabled PARENT_SCOPE)
  else()
    set(${__out} disabled PARENT_SCOPE)
  endif()
endfunction()

# The same configuration as JSON (tamm_build_config_json()), built in TAMM_CONFIG_JSON.
set(TAMM_CONFIG_JSON "{}")

# Sets the member at path <ARGN> of TAMM_CONFIG_JSON to <json> (any JSON value text).
function(tamm_json __json)
  string(JSON TAMM_CONFIG_JSON SET "${TAMM_CONFIG_JSON}" ${ARGN} "${__json}")
  set(TAMM_CONFIG_JSON "${TAMM_CONFIG_JSON}" PARENT_SCOPE)
endfunction()

# <value> as a JSON string.
function(tamm_json_string __out __value)
  string(REPLACE "\\" "\\\\" __value "${__value}")
  string(REPLACE "\"" "\\\"" __value "${__value}")
  string(REPLACE "\n" "\\n" __value "${__value}")
  string(REPLACE "\t" "\\t" __value "${__value}")
  string(REPLACE "\r" "" __value "${__value}")
  set(${__out} "\"${__value}\"" PARENT_SCOPE)
endfunction()

# The CMake truth value of <var> as a JSON boolean.
function(tamm_json_bool __out __var)
  if(${__var})
    set(${__out} true PARENT_SCOPE)
  else()
    set(${__out} false PARENT_SCOPE)
  endif()
endfunction()

# Versions line for one dependency: the user override when set, else the pin from
# dep_versions.cmake; commit hashes are shortened to 7 characters and marked "(commit)".
# "external (<path>)" when the user pointed CMakeBuild at <root>_ROOT.
function(tamm_config_version __label __root __override __pin)
  set(__tag ${${__pin}})
  if(__override)
    if(${__override})
      set(__tag ${${__override}})
    endif()
  endif()
  set(__full "${__tag}") # the JSON keeps full commit hashes
  if(__tag MATCHES "^[0-9a-f]+$" AND NOT __tag MATCHES "^[0-9]+$")
    string(LENGTH "${__tag}" __len)
    if(__len GREATER 7)
      string(SUBSTRING "${__tag}" 0 7 __tag)
    endif()
    set(__tag "${__tag} (commit)")
  endif()
  if(${__root}_ROOT)
    set(__tag "external (${${__root}_ROOT})")
    set(__full "${__tag}")
  endif()
  tamm_config_line("  " "${__label}" "${__tag}")
  tamm_json_string(__json "${__full}")
  tamm_json("${__json}" versions "${__label}")
  set(TAMM_CONFIG_TEXT "${TAMM_CONFIG_TEXT}" PARENT_SCOPE)
  set(TAMM_CONFIG_JSON "${TAMM_CONFIG_JSON}" PARENT_SCOPE)
endfunction()

function(tamm_config_versions)
  include(dep_versions) # CMakeBuild's pins; found through CMAKE_MODULE_PATH
  tamm_config_line("" "Versions" "")
  tamm_json("{}" versions)
  tamm_config_version("Global Arrays" GlobalArrays GA_TAG GA_GIT_TAG)
  if(USE_LIBNUMA)
    tamm_config_version(numactl numactl "" NUMACTL_GIT_TAG)
  endif()
  # CMakeBuild builds BLAS/LAPACK/ScaLAPACK only for BLIS/OpenBLAS (LAPACK and ScaLAPACK also for
  # IBMESSL); a vendor library has no pinned version, and the configuration already names it.
  if(LINALG_VENDOR STREQUAL "BLIS")
    tamm_config_version(BLIS BLIS BLIS_TAG BLIS_GIT_TAG)
  elseif(LINALG_VENDOR STREQUAL "OpenBLAS")
    tamm_config_version(OpenBLAS OpenBLAS "" OpenBLAS_GIT_TAG)
  endif()
  if(LINALG_VENDOR MATCHES "^(BLIS|OpenBLAS|IBMESSL)$")
    tamm_config_version(LAPACK LAPACK "" LAPACK_GIT_TAG)
    if(USE_SCALAPACK)
      tamm_config_version(ScaLAPACK ScaLAPACK "" SL_GIT_TAG)
    endif()
  endif()
  if(${PROJECT_NAME}_HAS_ELPA)
    tamm_config_version(ELPA ELPA "" CMSB_ELPA_VERSION)
  endif()
  tamm_config_version(NJSON NJSON "" CMSB_NJSON_VERSION)
  tamm_config_version(DOCTEST DOCTEST "" CMSB_DOCTEST_VERSION)
  tamm_config_version(SPDLOG SPDLOG "" SPDLOG_GIT_TAG)
  tamm_config_version(Eigen3 Eigen3 EIGEN_TAG EIGEN_GIT_TAG)
  tamm_config_version(HDF5 HDF5 "" CMSB_HDF5_VERSION)
  if(${PROJECT_NAME}_HAS_PYTHON)
    tamm_config_version(pybind11 pybind11 "" PYBIND_GIT_TAG)
  endif()
  if(MODULES)
    tamm_config_version(LibInt2 LibInt2 "" CMSB_LIBINT_VERSION)
    tamm_config_version(GauXC GauXC GAUXC_TAG GXC_GIT_TAG)
    tamm_config_version(EcpInt EcpInt "" ECPINT_GIT_TAG)
  endif()
  if(USE_NWQSIM)
    tamm_config_version(NWQSim NWQSim "" NWQSIM_GIT_TAG)
  endif()
  set(TAMM_CONFIG_TEXT "${TAMM_CONFIG_TEXT}" PARENT_SCOPE)
  set(TAMM_CONFIG_JSON "${TAMM_CONFIG_JSON}" PARENT_SCOPE)
endfunction()

# Build
tamm_config_line("" "Build type" "${CMAKE_BUILD_TYPE}")
# One line when the C, C++ and Fortran compilers are the same, else one line per language.
set(__cc "${CMAKE_C_COMPILER_ID} ${CMAKE_C_COMPILER_VERSION}")
set(__cxx "${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
set(__fc "${CMAKE_Fortran_COMPILER_ID} ${CMAKE_Fortran_COMPILER_VERSION}")
if(__cc STREQUAL __cxx AND __fc STREQUAL __cxx)
  tamm_config_line("" "Compilers" "${__cxx} (C, C++, Fortran)")
else()
  tamm_config_line("" "C compiler" "${__cc}")
  tamm_config_line("" "C++ compiler" "${__cxx}")
  tamm_config_line("" "Fortran compiler" "${__fc}")
endif()
if(MARCH_FLAGS) # only when the user set it; CMakeBuild's default is not passed here
  tamm_config_line("" "March flags" "${MARCH_FLAGS}")
endif()
tamm_config_enabled(__shared BUILD_SHARED_LIBS)
tamm_config_line("" "Shared libraries" "${__shared}")
tamm_config_line("" "Install prefix" "${CMAKE_INSTALL_PREFIX}")
set(MPI_DETERMINE_LIBRARY_VERSION TRUE) # FindMPI fills MPI_C_LIBRARY_VERSION_STRING only when set
find_package(MPI COMPONENTS C)
string(STRIP "${MPI_C_LIBRARY_VERSION_STRING}" __mpi)
tamm_config_blank()
tamm_config_line("" "MPI library" "")
tamm_config_append("${__mpi}") # printed as MPI reports it

tamm_json_string(__j "${CMAKE_BUILD_TYPE}")
tamm_json("${__j}" build_type)
tamm_json("{}" compilers)
foreach(__lang c:__cc cxx:__cxx fortran:__fc)
  string(REPLACE ":" ";" __lang "${__lang}")
  list(GET __lang 0 __key)
  list(GET __lang 1 __var)
  tamm_json_string(__j "${${__var}}")
  tamm_json("${__j}" compilers ${__key})
endforeach()
if(MARCH_FLAGS)
  tamm_json_string(__j "${MARCH_FLAGS}")
  tamm_json("${__j}" march_flags)
endif()
tamm_json_bool(__j BUILD_SHARED_LIBS)
tamm_json("${__j}" shared_libraries)
tamm_json_string(__j "${CMAKE_INSTALL_PREFIX}")
tamm_json("${__j}" install_prefix)
tamm_json_string(__j "${__mpi}")
tamm_json("${__j}" mpi_library)

# Parallelism
tamm_config_enabled(__openmp USE_OPENMP)
tamm_config_blank()
tamm_config_line("" "Parallelism" "")
tamm_config_line("  " "OpenMP" "${__openmp}")
tamm_config_line("  " "Global Arrays" "")
tamm_config_line("    " "Runtime" "${GA_RUNTIME}")
tamm_json_bool(__j USE_OPENMP)
tamm_json("{\"openmp\": ${__j}, \"global_arrays\": {}}" parallelism)
tamm_json_string(__j "${GA_RUNTIME}")
tamm_json("${__j}" parallelism global_arrays runtime)

# Memory
tamm_config_enabled(__libnuma USE_LIBNUMA)
tamm_config_blank()
tamm_config_line("" "Memory" "")
tamm_config_line("  " "libnuma" "${__libnuma}")
tamm_json_bool(__j USE_LIBNUMA)
tamm_json("{\"libnuma\": ${__j}}" memory)

# GPU
tamm_config_blank()
set(__gpu_backend "")
if(${PROJECT_NAME}_HAS_CUDA)
  set(__gpu_backend CUDA)
  set(__gpu_version "${CMAKE_CUDA_COMPILER_VERSION}")
  tamm_config_line("" "GPU support" "")
  tamm_config_line("  " "CUDA" "${__gpu_version}")
  tamm_config_line("  " "CUDA arch" "${GPU_ARCH}")
elseif(${PROJECT_NAME}_HAS_HIP)
  set(__gpu_backend HIP)
  set(__gpu_version "${CMAKE_HIP_COMPILER_VERSION}")
  tamm_config_line("" "GPU support" "")
  tamm_config_line("  " "HIP" "${__gpu_version}")
  tamm_config_line("  " "HIP arch" "${GPU_ARCH}")
elseif(${PROJECT_NAME}_HAS_DPCPP)
  set(__gpu_backend DPC++)
  set(__gpu_version "${CMAKE_CXX_COMPILER_VERSION}")
  tamm_config_line("" "GPU support" "")
  tamm_config_line("  " "DPC++" "${__gpu_version}")
  tamm_config_line("  " "DPC++ arch" "${GPU_ARCH}")
else()
  tamm_config_line("" "GPU support" "disabled")
endif()
if(__gpu_backend)
  tamm_json("{}" gpu)
  foreach(__key backend version arch)
    if(__key STREQUAL "backend")
      tamm_json_string(__j "${__gpu_backend}")
    elseif(__key STREQUAL "version")
      tamm_json_string(__j "${__gpu_version}")
    else()
      tamm_json_string(__j "${GPU_ARCH}")
    endif()
    tamm_json("${__j}" gpu ${__key})
  endforeach()
else()
  tamm_json(null gpu)
endif()

# Linear algebra
tamm_config_enabled(__scalapack USE_SCALAPACK)
tamm_config_enabled(__elpa ${PROJECT_NAME}_HAS_ELPA)
tamm_config_blank()
tamm_config_line("" "Linear algebra" "")
tamm_config_line("  " "BLAS" "${LINALG_VENDOR}")
if(BLAS_INT4)
  set(__blas_int 32)
else()
  set(__blas_int 64)
endif()
tamm_config_line("  " "BLAS integers" "${__blas_int}-bit")
tamm_config_line("  " "ScaLAPACK" "${__scalapack}")
tamm_config_line("  " "ELPA" "${__elpa}")
tamm_json_string(__j "${LINALG_VENDOR}")
tamm_json_bool(__jsl USE_SCALAPACK)
tamm_json_bool(__jel ${PROJECT_NAME}_HAS_ELPA)
tamm_json("{\"blas\": ${__j}, \"blas_integers\": ${__blas_int}, \"scalapack\": ${__jsl}, \"elpa\": ${__jel}}"
          linear_algebra)

# Language bindings
tamm_config_enabled(__python ${PROJECT_NAME}_HAS_PYTHON)
tamm_config_blank()
tamm_config_line("" "Language bindings" "")
tamm_config_line("  " "Python" "${__python}")
tamm_json_bool(__j ${PROJECT_NAME}_HAS_PYTHON)
tamm_json("{\"python\": ${__j}}" language_bindings)

# Modules
tamm_config_blank()
tamm_config_line("" "Modules" "")
set(__jmodules "")
foreach(__module ${MODULES})
  tamm_config_line("  " "${__module}" "enabled")
  tamm_json_string(__j "${__module}")
  list(APPEND __jmodules "${__j}")
endforeach()
if(MODULES)
  tamm_config_enabled(__gauxc_gpu GAUXC_GPU)
  tamm_config_line("  " "GauXC GPU" "${__gauxc_gpu}")
endif()
tamm_config_enabled(__nwqsim USE_NWQSIM)
tamm_config_line("  " "NWQSim" "${__nwqsim}")
list(JOIN __jmodules ", " __jmodules)
tamm_json_bool(__jgg GAUXC_GPU)
tamm_json_bool(__jnq USE_NWQSIM)
tamm_json("{\"enabled\": [${__jmodules}], \"gauxc_gpu\": ${__jgg}, \"nwqsim\": ${__jnq}}" modules)

# Versions
tamm_config_blank()
tamm_config_versions()

configure_file(${CMAKE_CURRENT_LIST_DIR}/tamm_config.hpp.in
               ${CMAKE_CURRENT_BINARY_DIR}/include/tamm/tamm_config.hpp @ONLY)
install(FILES ${CMAKE_CURRENT_BINARY_DIR}/include/tamm/tamm_config.hpp DESTINATION include/tamm)
